### PR TITLE
RFC: Slugify headers by default

### PR DESCRIPTION
**Pull request by ArtskydJ**

### CODE REVIEW

**Comment by TehShrike** [comment]
hmm... I suppose this wouldn't affect headers inside of embedded templates that hadn't loaded yet.  Maybe those aren't likely to matter?

I wonder if we should just do it before and after this `scan` call in noddity-render-dom: https://github.com/ArtskydJ/noddity-render-dom/blob/master/index.js#L58 or maybe even all the way back in [noddity-template-parser](https://github.com/TehShrike/noddity-template-parser)

**Comment by ArtskydJ** [comment]
Yeah, I think it should be done in `noddity-template-parser`.

https://github.com/jonschlinkert/remarkable/issues/122

We could extend remarkable:

```js
var md = new Remarkable().use(function (remarkable) {
  remarkable.renderer.rules.heading_open = function (tokens, idx) {
    return '<h' + tokens[idx].hLevel + ' id="' + slugify(tokens[idx + 1].content) + '">'
  }
})

function slugify(str) {
  return str.replace(/\W+/g, '-')
}
```

At this level, it might be harder guarantee unique IDs, since an embedded template might have the same header as its parent has.

**Comment by TehShrike** [comment]
Should this be recreated as an issue in `noddity-template-parser` then?

**Comment by ArtskydJ** [comment]
Yeah, it probably should.

**Pull request closed without merging**
